### ISSUE TITLE
Potential Memory Leak

### ISSUE THREAD

**Issue by Georgii-Shagov** [Refinitiv/Real-Time-SDK#176] opened 2021-06-09 12:38 UTC
Hello Team

From Valgrind testing
Environment
```
MS HyperV: Centos-7 64bits, 
Linux XXXXXXXXXXXX 3.10.0-1160.24.1.el7.x86_64 #1 SMP Thu Apr 8 19:51:47 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
```

```
gcc (GCC) 4.8.5 20150623 (Red Hat 4.8.5-44)
Copyright (C) 2015 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```

```
==25409== 864 (576 direct, 288 indirect) bytes in 24 blocks are definitely lost in loss record 23,228 of 24,573                                                                          
==25409==    at 0x4C2A593: operator new(unsigned long) (vg_replace_malloc.c:344)                                                                                                         
==25409==    by 0x7F57A0D8: refinitiv::ema::access::DirectoryServiceStore::decodeSourceDirectoryKeyUInt(RsslMap&, RsslDecIterator&, refinitiv::ema::access::EmaString&, int&) (in /home/XXXXXXXXXXXXXX/Linux_glibc-2.17_x86-64_64/lib/libema.so.3.6.0.0)                                                                                    
==25409==    by 0x7F57AD13: refinitiv::ema::access::DirectoryServiceStore::decodeSourceDirectory(RwfBuffer*, refinitiv::ema::access::EmaString&, int&) (in /home/XXXXXXXXXXXXXX/Linux_glibc-2.17_x86-64_64/lib/libema.so.3.6.0.0)                                                                                                           
==25409==    by 0x7F609F9C: refinitiv::ema::access::OmmIProviderImpl::submit(refinitiv::ema::access::RefreshMsg const&, unsigned long long) (in /home/XXXXXXXXXXXXXXXXXXXXXXXXXXXX
```

**Comment by fogol** [comment] 2021-06-10 12:39
@Georgii-Shagov Thank you for bringing this to our attention. We will investigate the issue. It will be fixed in further releases.

**Comment by ViktorYelizarov** [comment] 2021-07-09 15:48
@Georgii-Shagov 
I tested many cases but could not see the memory leak.
Could you please add more information or describe the scenario to reproduce this issue?

**Comment by vlevendel** [comment] 2022-01-27 14:47
@Georgii-Shagov Do you still see this issue?  Would you please respond to the questions from Viktor above?

**Comment by vlevendel** [comment] 2022-02-24 21:28
Closing due to inactivity. @Georgii-Shagov please feel free to reopen with required response to above questions.

**Closed by vlevendel** 2022-02-24 21:28 UTC
