### ISSUE TITLE
EMAJ: ema.access.DateTimeStringFormatImpl Observation

### ISSUE THREAD

**Issue by FrankConstructor** [Refinitiv/Real-Time-SDK#57] opened 2018-05-08 10:14 UTC
The fooAsString() methods seem to be implemented in an improvable way.

They (temporarily) change the internal state of the underlying upa object:
`_originalFormat = ommDtImpl._rsslDate.format();`
`ommDtImpl._rsslDate.format(_format);`
`_dtString = ommDtImpl._rsslDate.toString();`
`ommDtImpl._rsslDate.format(_originalFormat);`

Potentially, this could lead to problems regarding multi-threading as these four lines are not atomic.
A dedicated formatToString(int format) method in upa.codec.Date/Time could be more safe.

**Comment by bberner** [comment] 2018-05-08 13:37
Thank you for your feedback. A JIRA issue has been created and the issue is being investigated. We'll let you know if we need further information.

**Comment by vlevendel** [comment] 2020-09-16 00:49
@FrankConstructor Please review fix and let us know if you have further concerns. Closing.

**Closed by vlevendel** 2020-09-16 00:49 UTC
