### ISSUE TITLE
Issue with "MarketPriceEdpGwServiceDiscoveryExample" using "WebSocketSharp" in .NET Framework 3.5 - WebSocket API

### ISSUE THREAD

**Issue by VPDevGroup** [Refinitiv/Real-Time-SDK#167] opened 2021-02-03 03:10 UTC
Hi Team,

Need your help.

I am working with "MarketPriceEdpGwServiceDiscoveryExample" using "WebSocketSharp" in .NET Framework 3.5.

I am able to successfully do the authentication but facing issue with DiscoverServices()  method.
The error message is “The remote server returned an error: (401) Unauthorized.” (see the image below).

Could you please let me know your thoughts here.

Thanks
Pradeep B
![02-02-2021 09-21-54 PM](https://user-images.githubusercontent.com/20486956/106692943-76d80f80-65fb-11eb-9fab-16f1d5713d27.png)

**Comment by fogol** [comment] 2021-02-07 09:20
The issue is duplicated at [Refinitiv Developer Community](https://community.developers.refinitiv.com/questions/72677/webscoket-sharp-issue-in-discoverservices-method-f.html) and it is solved there. The issue could be closed.

**Comment by fogol** [comment] 2021-02-11 17:51
@VPDevGroup, 
 
We agree with the answer provided on Developer Portal which was added after you open the issue here.  To reiterate, it is recommended on the portal to use JSON package for .net. Please view the original issue for reference:
https://community.developers.refinitiv.com/questions/72677/webscoket-sharp-issue-in-discoverservices-method-f.html
 
Closing issue here unless there are more updates. If there are new issues, please open another issue.

**Closed** 2021-02-11 17:51 UTC
